# Generated by Django 2.0.8 on 2019-05-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_likedislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='dis_likes',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
